import React, { useState, useEffect } from 'react';
import axios from 'axios'; // Import axios
import api from '../api';
import { Module, Video, UserProgress, Course, Week, Day } from '../types/course'; // Assuming Course type exists or will be defined
import { Input } from '../components/ui/input';
import { Button } from '../components/ui/button';
import { Label } from '../components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '../components/ui/card';
import { PlusCircle, MinusCircle, Edit, Trash2, Save, Users, BarChart, VideoIcon } from 'lucide-react'; // Import icons
import { ProgressCard } from '../components/ProgressCard';
import { minutesToSeconds, secondsToMinutes } from '../utils/duration';
import { findVideoDuration } from '../utils/videoUtils';
import { getNoteTitle, setNoteTitle, getAutoGeneratedTitle } from '../utils/noteTitles';
import Header from '../components/Header';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../components/ui/dialog';
import { toast } from '@/components/ui/sonner';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '../components/ui/accordion'; // Import Accordion components
import { BarChart as RechartsBarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'; // Import Recharts components

interface User {
  _id: string;
  username: string;
  email: string;
  role: string;
}

interface DailyActivity {
  username: string;
  email: string;
  loginTime: string;
  logoutTime: string;
}


type ViewMode = 'overview' | 'users' | 'activity' | 'modules' | 'progress' | 'student-progress' | 'create-course' | 'manage-course'; // Added 'manage-course' view mode

const AdminDashboard: React.FC = () => {
  const [stats, setStats] = useState<{
    userCount: number;
    dailyCount: number;
    mostWatchedVideos: string[];
  }>({
    userCount: 0,
    dailyCount: 0,
    mostWatchedVideos: [],
  });
  const [selectedStudentId, setSelectedStudentId] = useState<string | null>(null);
  const [modules, setModules] = useState<Module[]>([]); // This will now represent modules within a selected course
  const [courses, setCourses] = useState<Course[]>([]); // State to hold all courses
  const [newModule, setNewModule] = useState<Module>({ title: '', concepts: '', exercises: '', videos: [{ title: '', url: '', duration: 0, notesUrl: [] }], assessments: [] }); // Initialize with empty notesUrl array and assessments
  const [editingModuleId, setEditingModuleId] = useState<string | null>(null);
  const [editedModule, setEditedModule] = useState<Module | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [selectedWeek, setSelectedWeek] = useState<number | null>(null);
  const [selectedDay, setSelectedDay] = useState<number | null>(null);
  const [editingWeekNumber, setEditingWeekNumber] = useState<number | null>(null); // Store week number when editing
  const [editingDayNumber, setEditingDayNumber] = useState<number | null>(null); // Store day number when editing
  const [newDayAssessment, setNewDayAssessment] = useState<string>(''); // State for new day assessment title
  const [newDayAssessmentLink, setNewDayAssessmentLink] = useState<string>(''); // State for new day assessment link
  const [dailyActivity, setDailyActivity] = useState<DailyActivity[]>([]);
  const [newModuleAssessments, setNewModuleAssessments] = useState<{ title: string; link: string }[]>([]);
  const [progress, setProgress] = useState<UserProgress[]>([]);
  const [viewMode, setViewMode] = useState<ViewMode>('overview'); // New state for view mode

  // State for creating a new course
  const [newCourse, setNewCourse] = useState<Course>({
    title: '',
    description: '',
    weeks: [], // Changed from modules to weeks
    skills: '',
    tools: '',
    level: 'beginner',
    duration: '0',
    _id: '',
  });
  const [selectedCourseIdForModules, setSelectedCourseIdForModules] = useState<string | null>(null); // To track which course's modules are being managed
  const [promoteUserDialogOpen, setPromoteUserDialogOpen] = useState(false);
  const [selectedUserIdForPromotion, setSelectedUserIdForPromotion] = useState<string | null>(null);
  const [adminKey, setAdminKey] = useState('');

  // Fetch course details including weeks, days, and modules
  const fetchCourseDetails = async (courseId: string) => {
    try {
      const res = await api.get<Course>(`/api/admin/courses/${courseId}`); // Assuming an endpoint to fetch a single course with its full structure
      // Flatten the modules for easier management in the current state structure
      const allModules: Module[] = [];
      res.weeks.forEach(week => {
        week.days.forEach(day => {
          day.modules.forEach(module => {
            allModules.push(module);
          });
        });
      });
      setModules(allModules);
      // Set the newCourse state to the fetched course for editing if needed
      setNewCourse(res);
    } catch (err) {
      console.error('Failed to fetch course details:', err);
    }
  };

  useEffect(() => {
    fetchStats();
    fetchCourses(); // Fetch courses when component mounts or viewMode changes
    // Fetch course details only when 'modules' view is active or when creating/editing a course
    if ((viewMode === 'modules' || viewMode === 'manage-course') && selectedCourseIdForModules) {
      fetchCourseDetails(selectedCourseIdForModules);
    }
    if (viewMode === 'users') {
      fetchUsers();
    }
    if (viewMode === 'activity') {
      fetchDailyActivity();
    }
    if (viewMode === 'progress' || viewMode === 'student-progress') {
      fetchUserProgress();
    }
  }, [viewMode, selectedStudentId, selectedCourseIdForModules]); // Re-fetch when viewMode, selectedStudentId, or selectedCourseIdForModules changes

  // Initial fetch for overview
  useEffect(() => {
    fetchStats();
    fetchCourses(); // Fetch courses on initial load
  }, []);

  const fetchStats = async () => {
    try {
      const res = await api.get<{ userCount: number; dailyCount: number; mostWatchedVideos: string[] }>('/api/admin/stats');
      setStats(res);
    } catch (err) {
      console.error('Failed to fetch stats:', err);
    }
  };

  const fetchUsers = async () => {
    try {
      const res = await api.get<User[]>('/api/admin/users');
      setUsers(res);
    } catch (err) {
      console.error('Failed to fetch users:', err);
    }
  };

  const handlePromoteToAdmin = async () => {
    if (!selectedUserIdForPromotion || !adminKey) {
      toast.error('Error', {
        description: 'Please enter the admin verification key',
      });
      return;
    }

    try {
      const res = await api.put<{ msg: string; user: User }>(`/api/admin/users/${selectedUserIdForPromotion}/role`, {
        adminVerificationKey: adminKey,
      });
      
      toast.success('Success', {
        description: res.msg || 'User role updated to admin successfully',
      });
      
      // Update the user in the local state
      setUsers(users.map(user => 
        user._id === selectedUserIdForPromotion 
          ? { ...user, role: 'admin' }
          : user
      ));
      
      // Close dialog and reset state
      setPromoteUserDialogOpen(false);
      setSelectedUserIdForPromotion(null);
      setAdminKey('');
    } catch (err: any) {
      console.error('Failed to promote user:', err);
      const errorMessage = err.response?.data?.msg || err.response?.data?.message || 'Failed to update user role. Please try again.';
      toast.error('Error', {
        description: errorMessage,
      });
    }
  };

  const openPromoteDialog = (userId: string) => {
    setSelectedUserIdForPromotion(userId);
    setAdminKey('');
    setPromoteUserDialogOpen(true);
  };

  const fetchDailyActivity = async () => {
    try {
      const res = await api.get<DailyActivity[]>('/api/admin/daily-activity');
      setDailyActivity(res);
    } catch (err) {
      console.error('Failed to fetch daily activity:', err);
    }
  };

  const fetchUserProgress = async () => {
    try {
      const res = await api.get<UserProgress[]>('/api/admin/progress');
      setProgress(res);
    } catch (err) {
      console.error('Failed to fetch user progress:', err);
    }
  };

  const fetchCourses = async () => {
    try {
      const res = await api.get<Course[]>('/api/admin/courses'); // Assuming an endpoint to fetch all courses
      setCourses(res);
    } catch (err) {
      console.error('Failed to fetch courses:', err);
    }
  };

  // Handlers for new module creation (within a course context)
  const handleNewModuleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target;
    setNewModule(prevModule => ({
      ...prevModule,
      [name]: value,
    }));
  };

  const handleNewVideoChange = (
    index: number,
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    const updatedVideos = newModule.videos.map((video, i) =>
      i === index ? { ...video, [e.target.name]: e.target.value } : video
    );
    setNewModule({ ...newModule, videos: updatedVideos });
  };

  const addNewVideoField = () => {
    setNewModule({
      ...newModule,
      videos: [...newModule.videos, { title: '', url: '', duration: 0, notesUrl: [''] }], // Initialize with empty notesUrl array
    });
  };

  const removeNewVideoField = (index: number) => {
    const updatedVideos = newModule.videos.filter((_, i) => i !== index);
    setNewModule({ ...newModule, videos: updatedVideos });
  };

  const handleNewVideoNotesUrlChange = (videoIndex: number, noteIndex: number, value: string) => {
    setNewModule(prevModule => {
      const updatedVideos = prevModule.videos.map((video, i) => {
        if (i === videoIndex) {
          const updatedNotes = [...(video.notesUrl || [])];
          updatedNotes[noteIndex] = value;
          return { ...video, notesUrl: updatedNotes };
        }
        return video;
      });
      return { ...prevModule, videos: updatedVideos };
    });
  };

  // Handler for submitting a new module to the selected course
  const handleSubmitNewModule = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedCourseIdForModules || selectedWeek === null || selectedDay === null) {
      alert('Please enter a course, week number, and day number.');
      return;
    }

    // Validate that all videos have valid duration (not zero)
    const invalidVideos = newModule.videos.filter(video => !video.duration || Number(video.duration) <= 0);
    if (invalidVideos.length > 0) {
      alert('Please ensure all videos have a video duration greater than zero (in minutes).');
      return;
    }

    // Validate assessments
    const invalidAssessments = newModule.assessments?.filter(assessment => !assessment.title.trim() || !assessment.link.trim());
    if (newModule.assessments && invalidAssessments && invalidAssessments.length > 0) {
      alert('Please ensure all assessments have a title and a link.');
      return;
    }

    try {
      // Ensure week exists, create if it doesn't
      const weekExists = await ensureWeekExists(selectedCourseIdForModules, selectedWeek);
      if (!weekExists) {
        alert('Failed to create or find week.');
        return;
      }

      // Ensure day exists, create if it doesn't
      const dayExists = await ensureDayExists(
        selectedCourseIdForModules,
        selectedWeek,
        selectedDay,
        newDayAssessment, // Pass assessment title
        newDayAssessmentLink // Pass assessment link
      );
      if (!dayExists) {
        alert('Failed to create or find day.');
        return;
      }

      // Convert minutes to seconds before sending
      const moduleToSubmit = {
        ...newModule,
        videos: newModule.videos.map(video => ({
          ...video,
          duration: minutesToSeconds(Number(video.duration))
        }))
      };

      // POST /api/admin/courses/:courseId/weeks/:weekNumber/days/:dayNumber/modules creates a new module
      const res = await api.post<Module>(
        `/api/admin/courses/${selectedCourseIdForModules}/weeks/${selectedWeek}/days/${selectedDay}/modules`,
        moduleToSubmit
      );
      alert('Module created successfully');
      setNewModule({ title: '', concepts: '', exercises: '', videos: [{ title: '', url: '', duration: 0, notesUrl: [''] }], assessments: [{ title: '', link: '' }] }); // Reset form
      // Keep week and day selected for next module
      fetchCourseDetails(selectedCourseIdForModules); // Refresh course details
    } catch (err) {
      console.error('Failed to create module:', err);
      alert('Failed to create module');
    }
  };

  const handleEditModule = (module: Module, weekNumber: number, dayNumber: number) => {
    setEditingModuleId(module._id || module.id || null);
    setEditingWeekNumber(weekNumber); // Store week number for update
    setEditingDayNumber(dayNumber); // Store day number for update
    setEditedModule({
      ...module,
      concepts: module.concepts || '', // Ensure concepts is set
      exercises: module.exercises || '', // Ensure exercises is set
      videos: module.videos.map(video => ({
        ...video,
        duration: video.duration ? secondsToMinutes(video.duration) : 0, // Convert seconds to minutes for display
        notesUrl: video.notesUrl || [], // Ensure notesUrl is an array
      })),
      assessments: module.assessments || [], // Ensure assessments is an array
    });
  };

  const handleEditedModuleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (editedModule) {
      const { name, value } = e.target;
      setEditedModule(prevModule => ({
        ...prevModule!,
        [name]: value,
      }));
    }
  };

  const handleEditedVideoChange = (
    index: number,
    e: React.ChangeEvent<HTMLInputElement>
  ) => {
    if (editedModule) {
      const updatedVideos = editedModule.videos.map((video, i) =>
        i === index ? { ...video, [e.target.name]: e.target.value } : video
      );
      setEditedModule({ ...editedModule, videos: updatedVideos });
    }
  };

  const addEditedVideoField = () => {
    if (editedModule) {
      setEditedModule({
        ...editedModule,
        videos: [...editedModule.videos, { title: '', url: '', duration: 0, notesUrl: [''] }], // Initialize with empty notesUrl array
      });
    }
  };

  const removeEditedVideoField = (index: number) => {
    if (editedModule) {
      const updatedVideos = editedModule.videos.filter((_, i) => i !== index);
      setEditedModule({ ...editedModule, videos: updatedVideos });
    }
  };

  const handleEditedVideoNotesUrlChange = (videoIndex: number, noteIndex: number, value: string) => {
    if (editedModule) {
      setEditedModule(prevModule => {
        const updatedVideos = prevModule!.videos.map((video, i) => {
          if (i === videoIndex) {
            const updatedNotes = [...(video.notesUrl || [])];
            updatedNotes[noteIndex] = value;
            return { ...video, notesUrl: updatedNotes };
          }
          return video;
        });
        return { ...prevModule!, videos: updatedVideos };
      });
    }
  };

  const handleUpdateModule = async () => {
    if (editedModule && editedModule._id && selectedCourseIdForModules) {
      // Validate that all videos have valid duration (not zero)
      const invalidVideos = editedModule.videos.filter(video => !video.duration || Number(video.duration) <= 0);
      if (invalidVideos.length > 0) {
        alert('Please ensure all videos have a video duration greater than zero (in minutes).');
        return;
      }

      // Validate assessments
      const invalidAssessments = editedModule.assessments?.filter(assessment => !assessment.title.trim() || !assessment.link.trim());
      if (editedModule.assessments && invalidAssessments && invalidAssessments.length > 0) {
        alert('Please ensure all assessments have a title and a link.');
        return;
      }
      
      try {
        // Convert minutes to seconds before sending
        const moduleToUpdate = {
          title: editedModule.title,
          concepts: editedModule.concepts || '',
          exercises: editedModule.exercises || '',
          videos: editedModule.videos.map(video => ({
            title: video.title,
            url: video.url,
            duration: minutesToSeconds(Number(video.duration)),
            notesUrl: video.notesUrl || []
          })),
          assessments: editedModule.assessments || [],
          courseId: selectedCourseIdForModules || null // Include courseId to prevent module sharing
        };
        
        // Update the module
        await api.put<Module>(`/api/admin/modules/${editedModule._id}`, moduleToUpdate);

        alert('Module updated successfully');
        setEditingModuleId(null);
        setEditedModule(null);
        setEditingWeekNumber(null);
        setEditingDayNumber(null);
        if (selectedCourseIdForModules) {
          fetchCourseDetails(selectedCourseIdForModules); // Refresh course details
        }
      } catch (err) {
        console.error('Failed to update module:', err);
        alert('Failed to update module');
      }
    } else {
      alert('Please ensure module ID and course are selected.');
    }
  };

  const handleDeleteModule = async (moduleId: string) => {
    if (window.confirm('Are you sure you want to delete this module?')) {
      try {
        // Assuming DELETE /api/admin/modules/:moduleId deletes a module
        const res = await api.delete<void>(`/api/admin/modules/${moduleId}`); // Assuming this endpoint still works for deleting a module
        alert('Module deleted successfully');
        if (selectedCourseIdForModules) {
          fetchCourseDetails(selectedCourseIdForModules); // Refresh course details
        }
      } catch (err) {
        console.error('Failed to delete module:', err);
        alert('Failed to delete module');
      }
    }
  };

  // --- Week and Day Management Handlers ---
  
  // Helper function to ensure week exists, create if it doesn't
  const ensureWeekExists = async (courseId: string, weekNumber: number): Promise<boolean> => {
    try {
      const course = await api.get<Course>(`/api/admin/courses/${courseId}`);
      const weekExists = course.weeks.some(w => w.weekNumber === weekNumber);
      
      if (!weekExists) {
        try {
          await api.post(`/api/admin/courses/${courseId}/weeks`, { weekNumber });
        } catch (error) {
          // If week already exists (400 error), that's fine
          if (axios.isAxiosError(error) && error.response?.status === 400) {
            return true;
          }
          throw error;
        }
      }
      return true;
    } catch (error) {
      console.error('Failed to ensure week exists:', error);
      return false;
    }
  };

  // Helper function to ensure day exists, create if it doesn't
  const ensureDayExists = async (courseId: string, weekNumber: number, dayNumber: number, assessment: string, assessmentLink: string): Promise<boolean> => {
    try {
      // First ensure week exists
      const weekOk = await ensureWeekExists(courseId, weekNumber);
      if (!weekOk) {
        return false;
      }

      // Then check and create day if needed
      const course = await api.get<Course>(`/api/admin/courses/${courseId}`);
      const week = course.weeks.find(w => w.weekNumber === weekNumber);
      
      if (!week) {
        return false;
      }

      const dayExists = week.days.some(d => d.dayNumber === dayNumber);
      if (!dayExists) {
        try {
          await api.post(`/api/admin/courses/${courseId}/weeks/${weekNumber}/days`, { dayNumber, assessment, assessmentLink });
        } catch (error) {
          // If day already exists (400 error), that's fine
          if (axios.isAxiosError(error) && error.response?.status === 400) {
            return true;
          }
          throw error;
        }
      }
      return true;
    } catch (error) {
      console.error('Failed to ensure day exists:', error);
      return false;
    }
  };

  const handleDeleteWeek = async (weekNumber: number) => {
    if (!selectedCourseIdForModules || !window.confirm(`Are you sure you want to delete Week ${weekNumber} and all its content?`)) {
      return;
    }
    try {
      await api.delete(`/api/admin/courses/${selectedCourseIdForModules}/weeks/${weekNumber}`);
      alert(`Week ${weekNumber} deleted successfully.`);
      fetchCourseDetails(selectedCourseIdForModules);
    } catch (error) {
      console.error('Failed to delete week:', error);
      alert('Failed to delete week.');
    }
  };

  const handleDeleteDay = async (weekNumber: number, dayNumber: number) => {
    if (!selectedCourseIdForModules || !window.confirm(`Are you sure you want to delete Day ${dayNumber} from Week ${weekNumber} and all its content?`)) {
      return;
    }
    try {
      await api.delete(`/api/admin/courses/${selectedCourseIdForModules}/weeks/${weekNumber}/days/${dayNumber}`);
      alert(`Day ${dayNumber} from Week ${weekNumber} deleted successfully.`);
      fetchCourseDetails(selectedCourseIdForModules);
    } catch (error) {
      console.error('Failed to delete day:', error);
      alert('Failed to delete day.');
    }
  };

  // --- New Course Creation Handlers ---

  const handleNewCourseChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    setNewCourse({ ...newCourse, [e.target.name]: e.target.value });
  };

  const handleCreateCourse = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      // Ensure the new course has an empty 'weeks' array if not already present
      const courseToCreate = { ...newCourse, weeks: newCourse.weeks || [] };
      const response = await api.post<Course>('/api/admin/courses', courseToCreate); // Assuming POST /api/admin/courses creates a new course
      alert('Course created successfully!');
      const newCourseReset = { title: '', description: '', weeks: [], skills: '', tools: '', level: 'beginner' as const, duration: '0', _id: '' };
      if (response && response._id) {
        newCourseReset._id = response._id;
        // Set the newly created course as the selected one for module management
        setSelectedCourseIdForModules(response._id);
        // Reset new day assessment fields
        setNewDayAssessment('');
        setNewDayAssessmentLink('');
      }
      setNewCourse(newCourseReset); // Reset form
      fetchCourses(); // Refresh the list of courses
      setViewMode('modules'); // Navigate to module management view
    } catch (err) {
      console.error('Failed to create course:', err);
      alert('Failed to create course');
    }
  };

  // Handler to select a course for module management
  const handleSelectCourseForModules = (courseId: string) => {
    setSelectedCourseIdForModules(courseId);
    setViewMode('modules'); // Switch to modules view
    fetchCourseDetails(courseId); // Fetch modules for the selected course
  };

  // Helper to group modules by week and then by day
  const groupModulesByWeekAndDay = (course: Course | null) => {
    const groupedByWeek: { [week: number]: { [day: number]: Module[] } } = {};
    if (course && course.weeks) {
      course.weeks.forEach(week => {
        if (!groupedByWeek[week.weekNumber]) {
          groupedByWeek[week.weekNumber] = {};
        }
        week.days.forEach(day => {
          if (!groupedByWeek[week.weekNumber][day.dayNumber]) {
            groupedByWeek[week.weekNumber][day.dayNumber] = [];
          }
          day.modules.forEach(module => {
            groupedByWeek[week.weekNumber][day.dayNumber].push(module);
          });
        });
      });
    }
    return groupedByWeek;
  };

  const currentCourse = courses.find(c => c._id === selectedCourseIdForModules) || null;
  const groupedContentByWeek = groupModulesByWeekAndDay(currentCourse);
  const sortedWeeks = Object.keys(groupedContentByWeek).map(Number).sort((a, b) => a - b);

  // --- Render Logic ---

  return (
    <>
      <Header />
      <div className="container mx-auto p-2 sm:p-4 pt-20 sm:pt-24">
        <h1 className="text-xl sm:text-2xl font-bold mb-4 px-2 sm:px-0">Admin Dashboard</h1>

      <div className="flex flex-wrap gap-2 sm:gap-4 mb-6 sm:mb-8 px-2 sm:px-0 overflow-x-auto pb-2">
        <Button onClick={() => setViewMode('overview')} variant={viewMode === 'overview' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Overview</Button>
        <Button onClick={() => setViewMode('users')} variant={viewMode === 'users' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Users</Button>
        <Button onClick={() => setViewMode('activity')} variant={viewMode === 'activity' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Daily Activity</Button>
        <Button onClick={() => setViewMode('progress')} variant={viewMode === 'progress' || viewMode === 'student-progress' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Progress</Button>
        <Button onClick={() => setViewMode('modules')} variant={viewMode === 'modules' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Manage Course Content</Button>
        <Button onClick={() => { setViewMode('create-course'); }} variant={viewMode === 'create-course' ? 'default' : 'outline'} className="text-xs sm:text-sm whitespace-nowrap">Create Course</Button>
      </div>

      {viewMode === 'overview' && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <Card className="bg-blue-100 dark:bg-blue-900">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 text-foreground">
              <CardTitle className="text-sm font-medium">Users</CardTitle>
              <Users className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent className="text-foreground">
              <div className="text-2xl font-bold">{stats.userCount}</div>
              <p className="text-xs text-muted-foreground">Total registered users</p>
            </CardContent>
          </Card>
          <Card className="bg-green-100 dark:bg-green-900">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 text-foreground">
              <CardTitle className="text-sm font-medium">Daily Activity</CardTitle>
              <BarChart className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent className="text-foreground">
              <div className="text-2xl font-bold">{stats.dailyCount}</div>
              <p className="text-xs text-muted-foreground">Users active today (placeholder)</p>
            </CardContent>
          </Card>
          <Card className="bg-purple-100 dark:bg-purple-900">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 text-foreground">
              <CardTitle className="text-sm font-medium">Most Watched Videos</CardTitle>
              <VideoIcon className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent className="text-foreground">
              <ul className="list-disc list-inside text-sm">
                {stats.mostWatchedVideos && stats.mostWatchedVideos.length > 0 ? (
                  stats.mostWatchedVideos.map((video, index) => (
                    <li key={index}>{video}</li>
                  ))
                ) : (
                  <li>No data available</li>
                )}
              </ul>
            </CardContent>
          </Card>
        </div>
      )}

      {viewMode === 'users' && (
        <div className="mt-4 sm:mt-8 px-2 sm:px-0">
          <h2 className="text-base sm:text-lg font-semibold mb-4">All Users</h2>
          <div className="grid grid-cols-1 gap-4">
            {users.length > 0 ? (
              users.map((user) => (
                <Card key={user._id} className="text-foreground">
                  <CardContent className="p-3 sm:p-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-sm sm:text-base truncate">{user.username}</p>
                      <p className="text-xs sm:text-sm text-muted-foreground truncate">{user.email}</p>
                      <p className="text-xs sm:text-sm text-muted-foreground">Role: {user.role}</p>
                    </div>
                    <div className="flex flex-col sm:flex-row gap-2 w-full sm:w-auto">
                      <Button onClick={() => {
                        setSelectedStudentId(user._id);
                        setViewMode('student-progress');
                      }} className="w-full sm:w-auto text-xs sm:text-sm">
                        View Progress
                      </Button>
                      {user.role === 'user' && (
                        <Button 
                          onClick={() => openPromoteDialog(user._id)} 
                          variant="outline"
                          className="w-full sm:w-auto text-xs sm:text-sm"
                        >
                          Make Admin
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))
            ) : (
              <p>No users found.</p>
            )}
          </div>
        </div>
      )}

      {viewMode === 'activity' && (
        <div className="mt-4 sm:mt-8 px-2 sm:px-0">
          <h2 className="text-base sm:text-lg font-semibold mb-4">Daily Activity</h2>
          <div className="grid grid-cols-1 gap-4">
            {dailyActivity.length > 0 ? (
              dailyActivity.map((activity, index) => (
                <Card key={index} className="text-foreground">
                  <CardContent className="p-3 sm:p-4">
                    <p className="font-semibold text-sm sm:text-base">{activity.username}</p>
                    <p className="text-xs sm:text-sm text-muted-foreground">Email: {activity.email}</p>
                    <p className="text-xs sm:text-sm text-muted-foreground">Login Time: {activity.loginTime}</p>
                    <p className="text-xs sm:text-sm text-muted-foreground">Logout Time: {activity.logoutTime}</p>
                  </CardContent>
                </Card>
              ))
            ) : (
              <p>No daily activity found for today.</p>
            )}
          </div>
        </div>
      )}

      {viewMode === 'modules' && (
        <div className="mt-4 sm:mt-8 px-2 sm:px-0">
          <h2 className="text-base sm:text-lg font-semibold mb-4">Manage Course Content</h2>
          {/* Course selection for module management */}
          <div className="mb-4 flex flex-col sm:flex-row sm:items-center gap-2 sm:gap-4">
            <div className="flex flex-col sm:flex-row sm:items-center gap-2 flex-1">
              <Label htmlFor="courseSelect" className="text-sm sm:text-base dark:text-gray-200 whitespace-nowrap">Select Course:</Label>
              <select
                id="courseSelect"
                value={selectedCourseIdForModules || ''}
                onChange={(e) => handleSelectCourseForModules(e.target.value)}
                className="p-2 border rounded flex-1 min-w-0
                 bg-white text-gray-900 border-gray-300 text-sm sm:text-base
                 focus:ring-indigo-500 focus:border-indigo-500
                 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600"
              >
                <option value="" disabled>--Select a Course--</option>
                {courses.map(course => (
                  <option key={course._id} value={course._id}>{course.title}</option>
                ))}
              </select>
            </div>
            {selectedCourseIdForModules && (
              <Button variant="outline" size="sm" onClick={() => setViewMode('manage-course')} className="text-xs sm:text-sm whitespace-nowrap">
                Manage Selected Course
              </Button>
            )}
          </div>

          {selectedCourseIdForModules && (
            <>
              <h3 className="text-sm sm:text-md font-semibold mb-2 break-words">Content for: {currentCourse?.title}</h3>

              {sortedWeeks.length > 0 ? (
                sortedWeeks.map(weekNumber => {
                  const weekContent = groupedContentByWeek[weekNumber];
                  const sortedDays = Object.keys(weekContent).map(Number).sort((a, b) => a - b);
                  return (
                    <div key={weekNumber} className="mb-6 sm:mb-8 border rounded-lg shadow-sm bg-gray-100 dark:bg-gray-900 p-3 sm:p-4">
                      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 sm:gap-4 mb-4">
                        <h4 className="text-xl sm:text-2xl font-bold text-gray-900 dark:text-gray-50">Week {weekNumber}</h4>
                        <Button variant="destructive" size="sm" onClick={() => handleDeleteWeek(weekNumber)} className="w-full sm:w-auto text-xs sm:text-sm">
                          <Trash2 className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Delete Week
                        </Button>
                      </div>
                      {sortedDays.map(dayNumber => {
                        const sortedModulesForDay = weekContent[dayNumber].sort((a, b) => (a.title || '').localeCompare(b.title || '')); // Sort modules by title
                        return (
                          <div key={`${weekNumber}-${dayNumber}`} className="mb-4 sm:mb-6 border rounded-lg shadow-sm bg-gray-50 dark:bg-gray-800 p-3 sm:p-4">
                            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 sm:gap-4 mb-4">
                              <h5 className="text-lg sm:text-xl font-bold text-gray-800 dark:text-gray-100">Day {dayNumber}</h5>
                              <Button variant="destructive" size="sm" onClick={() => handleDeleteDay(weekNumber, dayNumber)} className="w-full sm:w-auto text-xs sm:text-sm">
                                <Trash2 className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Delete Day
                              </Button>
                            </div>
                            <Accordion type="single" collapsible className="w-full">
                              {sortedModulesForDay.map((moduleItem) => (
                                <AccordionItem key={moduleItem._id || moduleItem.id} value={moduleItem._id || moduleItem.id || ''}>
                                  <AccordionTrigger>
                                    {editingModuleId === (moduleItem._id || moduleItem.id) ? (
                                      <div className="flex flex-col w-full">
                                        <Input
                                          type="text"
                                          name="title"
                                          value={editedModule?.title || ''}
                                          onChange={handleEditedModuleChange}
                                          onClick={(e) => e.stopPropagation()} // Prevent accordion from toggling
                                          className="w-full mb-2"
                                        />
                                      </div>
                                    ) : (
                                      moduleItem.title
                                    )}
                                  </AccordionTrigger>
                                  <AccordionContent>
                                    {editingModuleId === (moduleItem._id || moduleItem.id) ? (
                                      <div className="space-y-4 p-2 sm:p-4">
                                        <div>
                                          <Label htmlFor="editedModuleConcepts">Concepts</Label>
                                          <textarea
                                            id="editedModuleConcepts"
                                            name="concepts"
                                            value={editedModule?.concepts || ''}
                                            onChange={(e) => setEditedModule(prevModule => prevModule ? { ...prevModule, concepts: e.target.value } : null)}
                                            className="mt-1 block w-full rounded-md shadow-sm sm:text-sm p-2
                                             bg-white text-gray-900 placeholder-gray-500
                                             border border-gray-300
                                             focus:border-indigo-500 focus:ring-indigo-500
                                             dark:bg-gray-800 dark:border-gray-600 dark:text-gray-200 dark:placeholder-gray-400"
                                            rows={3}
                                            placeholder="Enter concepts covered in this module"
                                          />
                                        </div>
                                        <div>
                                          <Label htmlFor="editedModuleExercises">Exercises</Label>
                                          <textarea
                                            id="editedModuleExercises"
                                            name="exercises"
                                            value={editedModule?.exercises || ''}
                                            onChange={(e) => setEditedModule(prevModule => prevModule ? { ...prevModule, exercises: e.target.value } : null)}
                                            className="mt-1 block w-full rounded-md shadow-sm sm:text-sm p-2
                                             bg-white text-gray-900 placeholder-gray-500
                                             border border-gray-300
                                             focus:border-indigo-500 focus:ring-indigo-500
                                             dark:bg-gray-800 dark:border-gray-600 dark:text-gray-200 dark:placeholder-gray-400"
                                            rows={3}
                                            placeholder="Enter exercises for this module"
                                          />
                                        </div>
                                        <h3 className="text-sm sm:text-md font-semibold mt-4 sm:mt-6 mb-2">Videos</h3>
                                        {editedModule?.videos.map((video, index) => (
                                          <Card key={index} className="mb-4 p-3 sm:p-4 text-foreground">
                                            <CardContent>
                                              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 sm:gap-4">
                                                <div>
                                                  <Label htmlFor={`editedVideoTitle-${index}`}>Video Title</Label>
                                                  <Input
                                                    id={`editedVideoTitle-${index}`}
                                                    type="text"
                                                    name="title"
                                                    value={video.title}
                                                    onChange={(e) => handleEditedVideoChange(index, e)}
                                                    required
                                                  />
                                                </div>
                                                <div>
                                                  <Label htmlFor={`editedVideoUrl-${index}`}>Video URL</Label>
                                                  <Input
                                                    id={`editedVideoUrl-${index}`}
                                                    type="url"
                                                    name="url"
                                                    value={video.url}
                                                    onChange={(e) => handleEditedVideoChange(index, e)}
                                                    required
                                                  />
                                                </div>
                                                <div>
                                                  <Label>Notes (Optional)</Label>
                                                  <p className="text-xs text-muted-foreground mb-2">
                                                    Enter URL. A user-friendly title will be auto-generated, or you can customize it below.
                                                  </p>
                                                  {video.notesUrl?.map((note, noteIndex) => {
                                                    const autoTitle = note ? getAutoGeneratedTitle(note) : '';
                                                    const customTitle = note ? getNoteTitle(note) : '';
                                                    const displayTitle = customTitle !== autoTitle ? customTitle : '';
                                                    return (
                                                      <div key={noteIndex} className="space-y-2 p-3 border rounded-md mb-2">
                                                        <Input
                                                          type="url"
                                                          value={note}
                                                          onChange={(e) => {
                                                            handleEditedVideoNotesUrlChange(index, noteIndex, e.target.value);
                                                            // Auto-update title when URL changes
                                                            if (e.target.value.trim() && editedModule) {
                                                              setTimeout(() => {
                                                                setEditedModule(prev => prev ? { ...prev } : null);
                                                              }, 100);
                                                            }
                                                          }}
                                                          placeholder={`Note URL ${noteIndex + 1}`}
                                                          className="mb-2"
                                                        />
                                                        <div className="flex items-center gap-2">
                                                          <div className="flex-1">
                                                            <Label className="text-xs text-muted-foreground mb-1 block">
                                                              Title (auto-generated: "{autoTitle}")
                                                            </Label>
                                                            <Input
                                                              type="text"
                                                              value={displayTitle}
                                                              onChange={(e) => {
                                                                if (note) {
                                                                  setNoteTitle(note, e.target.value);
                                                                  // Trigger re-render
                                                                  if (editedModule) {
                                                                    setEditedModule(prev => prev ? { ...prev } : null);
                                                                  }
                                                                }
                                                              }}
                                                              placeholder={autoTitle || 'Enter custom title...'}
                                                              className="flex-1"
                                                            />
                                                          </div>
                                                          <Button
                                                            type="button"
                                                            variant="outline"
                                                            size="icon"
                                                            onClick={() => {
                                                              if (editedModule) {
                                                                setEditedModule(prevModule => {
                                                                  const updatedVideos = prevModule!.videos.map((v, i) => {
                                                                    if (i === index) {
                                                                      const updatedNotes = (v.notesUrl || []).filter((_, idx) => idx !== noteIndex);
                                                                      return { ...v, notesUrl: updatedNotes };
                                                                    }
                                                                    return v;
                                                                  });
                                                                  return { ...prevModule!, videos: updatedVideos };
                                                                });
                                                              }
                                                            }}
                                                            className="mt-6"
                                                          >
                                                            <MinusCircle className="w-4 h-4" />
                                                          </Button>
                                                        </div>
                                                      </div>
                                                    );
                                                  })}
                                                  <Button
                                                    type="button"
                                                    variant="outline"
                                                    size="sm"
                                                    onClick={() => {
                                                      if (editedModule) {
                                                        setEditedModule(prevModule => {
                                                          const updatedVideos = prevModule!.videos.map((v, i) => {
                                                            if (i === index) {
                                                              return { ...v, notesUrl: [...(v.notesUrl || []), ''] };
                                                            }
                                                            return v;
                                                          });
                                                          return { ...prevModule!, videos: updatedVideos };
                                                        });
                                                      }
                                                    }}
                                                    className="mb-4"
                                                  >
                                                    <PlusCircle className="w-4 h-4 mr-2" /> Add Note
                                                  </Button>
                                                </div>
                                                <div>
                                                  <Label htmlFor={`editedDuration-${index}`}>
                                                    Video Duration (minutes) *
                                                  </Label>
                                                  <Input
                                                    id={`editedDuration-${index}`}
                                                    type="number"
                                                    name="duration"
                                                    min="1"
                                                    step="0.1"
                                                    value={video.duration || ''}
                                                    onChange={(e) => handleEditedVideoChange(index, e)}
                                                    required
                                                  />
                                                </div>
                                              </div>
                                              <Button
                                                type="button"
                                                variant="destructive"
                                                onClick={() => removeEditedVideoField(index)}
                                                className="mt-4"
                                              >
                                                Remove Video
                                              </Button>
                                            </CardContent>
                                          </Card>
                                        ))}
                                        <div className="flex flex-wrap gap-2">
                                          <Button type="button" onClick={addEditedVideoField} className="text-xs sm:text-sm">
                                            <PlusCircle className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Add Video
                                          </Button>
                                        </div>

                                        <h3 className="text-sm sm:text-md font-semibold mt-4 sm:mt-6 mb-2">Exercises</h3>
                                        {editedModule?.assessments?.map((assessment, assessmentIndex) => (
                                          <Card key={assessmentIndex} className="mb-4 p-3 sm:p-4 text-foreground">
                                            <CardContent>
                                              <div>
                                                <Label htmlFor={`editedAssessmentTitle-${assessmentIndex}`}>Exercise Title</Label>
                                                <Input
                                                  id={`editedAssessmentTitle-${assessmentIndex}`}
                                                  type="text"
                                                  value={assessment.title}
                                                  onChange={(e) => {
                                                    if (editedModule) {
                                                      const updatedAssessments = [...(editedModule.assessments || [])];
                                                      updatedAssessments[assessmentIndex] = { ...updatedAssessments[assessmentIndex], title: e.target.value };
                                                      setEditedModule({ ...editedModule, assessments: updatedAssessments });
                                                    }
                                                  }}
                                                  required
                                                />
                                              </div>
                                              <div className="mt-2">
                                                <Label htmlFor={`editedAssessmentLink-${assessmentIndex}`}>Exercise Link</Label>
                                                <Input
                                                  id={`editedAssessmentLink-${assessmentIndex}`}
                                                  type="url"
                                                  value={assessment.link}
                                                  onChange={(e) => {
                                                    if (editedModule) {
                                                      const updatedAssessments = [...(editedModule.assessments || [])];
                                                      updatedAssessments[assessmentIndex] = { ...updatedAssessments[assessmentIndex], link: e.target.value };
                                                      setEditedModule({ ...editedModule, assessments: updatedAssessments });
                                                    }
                                                  }}
                                                  required
                                                />
                                              </div>
                                              <Button
                                                type="button"
                                                variant="destructive"
                                                onClick={() => {
                                                  if (editedModule) {
                                                    const updatedAssessments = (editedModule.assessments || []).filter((_, i) => i !== assessmentIndex);
                                                    setEditedModule({ ...editedModule, assessments: updatedAssessments });
                                                  }
                                                }}
                                                className="mt-4 text-xs sm:text-sm"
                                              >
                                                Remove Exercise
                                              </Button>
                                            </CardContent>
                                          </Card>
                                        ))}
                                        <div className="flex flex-wrap gap-2">
                                          <Button type="button" onClick={() => {
                                            if (editedModule) {
                                              setEditedModule({ ...editedModule, assessments: [...(editedModule.assessments || []), { title: '', link: '' }] });
                                            }
                                          }} className="text-xs sm:text-sm">
                                            <PlusCircle className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Add Exercise
                                          </Button>
                                          <Button onClick={handleUpdateModule} className="text-xs sm:text-sm">
                                            <Save className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Save Changes
                                          </Button>
                                          <Button variant="outline" onClick={() => {
                                            setEditingModuleId(null);
                                            setEditedModule(null);
                                            setEditingWeekNumber(null);
                                            setEditingDayNumber(null);
                                          }} className="text-xs sm:text-sm">
                                            Cancel
                                          </Button>
                                        </div>
                                      </div>
                                    ) : (
                                      <div className="flex flex-col sm:flex-row justify-end gap-2 p-2 sm:p-4">
                                        <Button variant="outline" size="sm" onClick={() => handleEditModule(moduleItem, weekNumber, dayNumber)} className="w-full sm:w-auto text-xs sm:text-sm">
                                          <Edit className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Edit
                                        </Button>
                                        <Button variant="destructive" size="sm" onClick={() => handleDeleteModule(moduleItem._id || moduleItem.id || '')} className="w-full sm:w-auto text-xs sm:text-sm">
                                          <Trash2 className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Delete
                                        </Button>
                                      </div>
                                    )}
                                    <div className="space-y-2 p-4">
                                      {moduleItem.videos.map((video) => (
                                        <div key={video._id} className="border p-2 rounded">
                                          <p className="font-semibold">{video.title}</p>
                                          <p className="text-sm text-muted-foreground">{video.url}</p>
                                        </div>
                                      ))}
                                    </div>
                                  </AccordionContent>
                                </AccordionItem>
                              ))}
                            </Accordion>
                          </div>
                        );
                      })}
                    </div>
                  );
                })
              ) : (
                <p>No content found for this course. Add weeks, days, and modules.</p>
              )}

              <div className="mt-6 sm:mt-8">
                <h2 className="text-base sm:text-lg font-semibold mb-4">Create New Module</h2>
                <form onSubmit={handleSubmitNewModule} className="space-y-4">
                  <div>
                    <Label htmlFor="moduleTitle">Module Title</Label>
                    <Input
                      id="moduleTitle"
                      type="text"
                      name="title"
                      value={newModule.title}
                      onChange={handleNewModuleChange}
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="moduleWeek">Week Number</Label>
                    <Input
                      id="moduleWeek"
                      type="number"
                      value={selectedWeek || ''}
                      onChange={(e) => setSelectedWeek(Number(e.target.value) || null)}
                      min="1"
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="moduleDay">Day Number</Label>
                    <Input
                      id="moduleDay"
                      type="number"
                      value={selectedDay || ''}
                      onChange={(e) => setSelectedDay(Number(e.target.value) || null)}
                      min="1"
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="moduleConcepts">Concepts (Optional)</Label>
                    <textarea
                      id="moduleConcepts"
                      name="concepts"
                      value={newModule.concepts || ''}
                      onChange={(e) => setNewModule({ ...newModule, concepts: e.target.value })}
                      className="mt-1 block w-full rounded-md shadow-sm sm:text-sm p-2
                       bg-white text-gray-900 placeholder-gray-500
                       border border-gray-300
                       focus:border-indigo-500 focus:ring-indigo-500
                       dark:bg-gray-800 dark:border-gray-600 dark:text-gray-200 dark:placeholder-gray-400"
                      rows={3}
                      placeholder="Enter concepts covered in this module"
                    />
                  </div>
                  <div>
                    <Label htmlFor="moduleExercises">Exercises (Optional)</Label>
                    <textarea
                      id="moduleExercises"
                      name="exercises"
                      value={newModule.exercises || ''}
                      onChange={(e) => setNewModule({ ...newModule, exercises: e.target.value })}
                      className="mt-1 block w-full rounded-md shadow-sm sm:text-sm p-2
                       bg-white text-gray-900 placeholder-gray-500
                       border border-gray-300
                       focus:border-indigo-500 focus:ring-indigo-500
                       dark:bg-gray-800 dark:border-gray-600 dark:text-gray-200 dark:placeholder-gray-400"
                      rows={3}
                      placeholder="Enter exercises for this module"
                    />
                  </div>
                  <h3 className="text-sm sm:text-md font-semibold mt-4 sm:mt-6 mb-2">Videos</h3>
                  {newModule.videos.map((video, videoIndex) => (
                    <Card key={videoIndex} className="mb-4 p-3 sm:p-4 text-foreground">
                      <CardContent>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 sm:gap-4">
                          <div>
                            <Label htmlFor={`newVideoTitle-${videoIndex}`}>Video Title</Label>
                            <Input
                              id={`newVideoTitle-${videoIndex}`}
                              type="text"
                              name="title"
                              value={video.title}
                              onChange={(e) => handleNewVideoChange(videoIndex, e)}
                              required
                            />
                          </div>
                          <div>
                            <Label htmlFor={`newVideoUrl-${videoIndex}`}>Video URL</Label>
                            <Input
                              id={`newVideoUrl-${videoIndex}`}
                              type="url"
                              name="url"
                              value={video.url}
                              onChange={(e) => handleNewVideoChange(videoIndex, e)}
                              required
                            />
                          </div>
                          <div>
                            <Label htmlFor={`newDuration-${videoIndex}`}>
                              Video Duration (minutes) *
                            </Label>
                            <Input
                              id={`newDuration-${videoIndex}`}
                              type="number"
                              name="duration"
                              min="1"
                              step="0.1"
                              value={video.duration || ''}
                              onChange={(e) => handleNewVideoChange(videoIndex, e)}
                              required
                            />
                          </div>
                        </div>
                        <div className="mt-4 space-y-2">
                          <Label>Notes (Optional)</Label>
                          <p className="text-xs text-muted-foreground mb-2">
                            Enter URL. A user-friendly title will be auto-generated, or you can customize it below.
                          </p>
                          {video.notesUrl?.map((note, noteIndex) => {
                            const autoTitle = note ? getAutoGeneratedTitle(note) : '';
                            const customTitle = note ? getNoteTitle(note) : '';
                            const displayTitle = customTitle !== autoTitle ? customTitle : '';
                            return (
                              <div key={noteIndex} className="space-y-2 p-3 border rounded-md">
                                <Input
                                  type="url"
                                  value={note}
                                  onChange={(e) => {
                                    handleNewVideoNotesUrlChange(videoIndex, noteIndex, e.target.value);
                                    // Auto-update title when URL changes
                                    if (e.target.value.trim()) {
                                      // Trigger re-render to show new auto-generated title
                                      setTimeout(() => {
                                        setNewModule(prev => ({ ...prev }));
                                      }, 100);
                                    }
                                  }}
                                  placeholder={`Note URL ${noteIndex + 1}`}
                                  className="mb-2"
                                />
                                <div className="flex items-center gap-2">
                                  <div className="flex-1">
                                    <Label className="text-xs text-muted-foreground mb-1 block">
                                      Title (auto-generated: "{autoTitle}")
                                    </Label>
                                    <Input
                                      type="text"
                                      value={displayTitle}
                                      onChange={(e) => {
                                        if (note) {
                                          setNoteTitle(note, e.target.value);
                                          // Trigger re-render by updating state
                                          setNewModule(prev => ({ ...prev }));
                                        }
                                      }}
                                      placeholder={autoTitle || 'Enter custom title...'}
                                      className="flex-1"
                                    />
                                  </div>
                                  <Button
                                    type="button"
                                    variant="outline"
                                    size="icon"
                                    onClick={() => {
                                      const updatedNotes = (video.notesUrl || []).filter((_, i) => i !== noteIndex);
                                      setNewModule(prevModule => {
                                        const updatedVideos = prevModule.videos.map((v, i) => {
                                          if (i === videoIndex) {
                                            return { ...v, notesUrl: updatedNotes };
                                          }
                                          return v;
                                        });
                                        return { ...prevModule, videos: updatedVideos };
                                      });
                                    }}
                                    className="mt-6"
                                  >
                                    <MinusCircle className="w-4 h-4" />
                                  </Button>
                                </div>
                              </div>
                            );
                          })}
                          <Button
                            type="button"
                            variant="outline"
                            size="sm"
                            onClick={() => {
                              setNewModule(prevModule => {
                                const updatedVideos = prevModule.videos.map((v, i) => {
                                  if (i === videoIndex) {
                                    return { ...v, notesUrl: [...(v.notesUrl || []), ''] };
                                  }
                                  return v;
                                });
                                return { ...prevModule, videos: updatedVideos };
                              });
                            }}
                          >
                            <PlusCircle className="w-4 h-4 mr-2" /> Add Note
                          </Button>
                        </div>
                        <Button
                          type="button"
                          variant="destructive"
                          onClick={() => removeNewVideoField(videoIndex)}
                          className="mt-4"
                        >
                          Remove Video
                        </Button>
                      </CardContent>
                    </Card>
                  ))}
                  <div className="flex flex-wrap gap-2">
                    <Button type="button" onClick={addNewVideoField} className="text-xs sm:text-sm">
                      <PlusCircle className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Add Video
                    </Button>
                  </div>

                  <h3 className="text-sm sm:text-md font-semibold mt-4 sm:mt-6 mb-2">Exercise</h3>
                  {newModule.assessments?.map((assessment, assessmentIndex) => (
                    <Card key={assessmentIndex} className="mb-4 p-4 text-foreground">
                      <CardContent>
                        <div>
                          <Label htmlFor={`newAssessmentTitle-${assessmentIndex}`}>Exercise Title</Label>
                          <Input
                            id={`newAssessmentTitle-${assessmentIndex}`}
                            type="text"
                            value={assessment.title}
                            onChange={(e) => {
                              const updatedAssessments = [...(newModule.assessments || [])];
                              updatedAssessments[assessmentIndex] = { ...updatedAssessments[assessmentIndex], title: e.target.value };
                              setNewModule({ ...newModule, assessments: updatedAssessments });
                            }}
                            required
                          />
                        </div>
                        <div className="mt-2">
                          <Label htmlFor={`newAssessmentLink-${assessmentIndex}`}>Exercise Link</Label>
                          <Input
                            id={`newAssessmentLink-${assessmentIndex}`}
                            type="url"
                            value={assessment.link}
                            onChange={(e) => {
                              const updatedAssessments = [...(newModule.assessments || [])];
                              updatedAssessments[assessmentIndex] = { ...updatedAssessments[assessmentIndex], link: e.target.value };
                              setNewModule({ ...newModule, assessments: updatedAssessments });
                            }}
                            required
                          />
                        </div>
                        <Button
                          type="button"
                          variant="destructive"
                          onClick={() => {
                            const updatedAssessments = (newModule.assessments || []).filter((_, i) => i !== assessmentIndex);
                            setNewModule({ ...newModule, assessments: updatedAssessments });
                          }}
                          className="mt-4"
                        >
                          Remove Exercise
                        </Button>
                      </CardContent>
                    </Card>
                  ))}
                  <div className="flex flex-wrap gap-2">
                    <Button type="button" onClick={() => setNewModule({ ...newModule, assessments: [...(newModule.assessments || []), { title: '', link: '' }] })} className="text-xs sm:text-sm">
                      <PlusCircle className="w-3 h-3 sm:w-4 sm:h-4 mr-1 sm:mr-2" /> Add Exercise
                    </Button>
                    <Button type="submit" disabled={selectedWeek === null || selectedDay === null} className="text-xs sm:text-sm">
                      Create Module
                    </Button>
                  </div>
                </form>
              </div>
            </>
          )}
        </div>
      )}

      {viewMode === 'create-course' && (
        <div className="mt-4 sm:mt-8 px-2 sm:px-0">
          <h2 className="text-base sm:text-lg font-semibold mb-4">Create New Course</h2>
          <form onSubmit={handleCreateCourse} className="space-y-4">
            <div>
              <Label htmlFor="courseTitle">Course Title</Label>
              <Input
                id="courseTitle"
                type="text"
                name="title"
                value={newCourse.title}
                onChange={handleNewCourseChange}
                required
              />
            </div>
            <div>
              <Label htmlFor="courseDescription">Course Description</Label>
              <textarea
                id="courseDescription"
                name="description"
                value={newCourse.description}
                onChange={handleNewCourseChange}
                className="mt-1 block w-full rounded-md shadow-sm sm:text-sm p-2
             bg-white text-gray-900 placeholder-gray-500
             border border-gray-300
             focus:border-indigo-500 focus:ring-indigo-500
             dark:bg-gray-800 dark:border-gray-600 dark:text-gray-200 dark:placeholder-gray-400"
                required
              />
            </div>
            <div>
              <Label htmlFor="courseSkills">Skills</Label>
              <Input
                id="courseSkills"
                type="text"
                name="skills"
                value={newCourse.skills}
                onChange={handleNewCourseChange}
                required
              />
            </div>
            <div>
              <Label htmlFor="courseTools">Tools</Label>
              <Input
                id="courseTools"
                type="text"
                name="tools"
                value={newCourse.tools}
                onChange={handleNewCourseChange}
                required
              />
            </div>
            <div>
              <Label htmlFor="courseLevel">Level</Label>
              <select
                id="courseLevel"
                name="level"
                value={newCourse.level}
                onChange={handleNewCourseChange}
                className="p-2 border rounded mt-1 block w-full shadow-sm sm:text-sm
             bg-white text-gray-900 border-gray-300
             focus:border-indigo-500 focus:ring-indigo-500
             dark:bg-gray-800 dark:text-gray-200 dark:border-gray-600"
                required
              >
                <option value="beginner">Beginner</option>
                <option value="intermediate">Intermediate</option>
                <option value="advanced">Advanced</option>
              </select>
            </div>
            <div>
              <Label htmlFor="courseDuration">Total Course Duration (e.g., "10 hours", "5 weeks")</Label>
              <Input
                id="courseDuration"
                type="text"
                name="duration"
                value={newCourse.duration}
                onChange={handleNewCourseChange}
                placeholder="e.g., 10 hours"
                required
              />
            </div>
            <div className="flex flex-wrap gap-2">
              <Button type="submit" className="text-xs sm:text-sm">Create Course</Button>
              <Button type="button" variant="outline" onClick={() => setViewMode('overview')} className="text-xs sm:text-sm">Cancel</Button>
            </div>
          </form>
        </div>
      )}

      {viewMode === 'manage-course' && selectedCourseIdForModules && (
        <div className="mt-8">
          <h2 className="text-lg font-semibold mb-4">Manage Course: {currentCourse?.title}</h2>
          <Button variant="outline" onClick={() => setViewMode('modules')} className="mb-4">
            Back to Course Content Management
          </Button>
          {/* This section could potentially show course details and allow editing them */}
          {/* For now, it just serves as a confirmation and a way to go back */}
        </div>
      )}

      {(viewMode === 'progress' || viewMode === 'student-progress') && (
        <div className="mt-4 sm:mt-8 px-2 sm:px-0">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-2 sm:gap-4 mb-4">
            <h2 className="text-base sm:text-lg font-semibold">
              {selectedStudentId ? `Progress for ${users.find(u => u._id === selectedStudentId)?.username || 'Unknown'}` : 'All Progress'}
            </h2>
            {selectedStudentId && (
              <Button onClick={() => { setSelectedStudentId(null); setViewMode('progress'); }} variant="outline" className="w-full sm:w-auto text-xs sm:text-sm">
                Back to All Students
              </Button>
            )}
          </div>
          <div className="grid grid-cols-1 gap-4">
            {progress.length > 0 ? (
              progress
                .filter(item => (selectedStudentId ? item.user._id === selectedStudentId : true))
                .map((item) => {
                  const lessonDuration = findVideoDuration(courses, item.lessonId) || 1;

                  return (
                    <ProgressCard
                      key={item._id}
                      lessonTitle={item.lessonTitle}
                      watchedSeconds={item.watchedSeconds}
                      lessonDuration={lessonDuration}
                      updatedAt={item.updatedAt}
                      completed={item.completed}
                      userInfo={{
                        username: item.user.username,
                        email: item.user.email,
                      }}
                    />
                  );
                })
            ) : (
              <p>No Progress found.</p>
            )}
          </div>
        </div>
      )}

      {/* Dialog for promoting user to admin */}
      <Dialog open={promoteUserDialogOpen} onOpenChange={setPromoteUserDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Promote User to Admin</DialogTitle>
            <DialogDescription>
              Enter the admin verification key to promote this user to admin role.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="adminKey">Admin Verification Key</Label>
              <Input
                id="adminKey"
                type="password"
                value={adminKey}
                onChange={(e) => setAdminKey(e.target.value)}
                placeholder="Enter admin verification key"
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    handlePromoteToAdmin();
                  }
                }}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => {
              setPromoteUserDialogOpen(false);
              setAdminKey('');
              setSelectedUserIdForPromotion(null);
            }}>
              Cancel
            </Button>
            <Button onClick={handlePromoteToAdmin}>
              Promote to Admin
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      </div>
    </>
  );
};

export default AdminDashboard;
